try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal

MEDIA_SORT = Literal["ID", "ID_DESC", "TITLE_ROMAJI", "TITLE_ROMAJI_DESC", "TITLE_ENGLISH",
                     "TITLE_ENGLISH_DESC", "TITLE_NATIVE", "TITLE_NATIVE_DESC", "TYPE", "TYPE_DESC", "FORMAT",
                     "FORMAT_DESC", "START_DATE", "START_DATE_DESC", "END_DATE", "END_DATE_DESC", "SCORE", "SCORE_DESC",
                     "POPULARITY", "POPULARITY_DESC", "TRENDING", "TRENDING_DESC", "EPISODES", "EPISODES_DESC",
                     "DURATION", "DURATION_DESC", "STATUS", "STATUS_DESC", "CHAPTERS", "CHAPTERS_DESC", "VOLUMES",
                     "VOLUMES_DESC", "UPDATED_AT", "UPDATED_AT_DESC", "SEARCH_MATCH", "FAVOURITES", "FAVOURITES_DESC"]
MEDIA_TYPE = Literal["ANIME", "MANGA"]
MEDIA_FORMAT = Literal["TV", "TV_SHORT", "MOVIE", "SPECIAL", "OVA", "ONA", "MUSIC", "MANGA", "NOVEL", "ONE_SHOT"]
MEDIA_STATUS = Literal["FINISHED", "RELEASING", "NOT_YET_RELEASED", "CANCELLED", "HIATUS"]
MEDIA_SOURCE = Literal["ORIGINAL", "MANGA", "LIGHT_NOVEL", "VISUAL_NOVEL", "VIDEO_GAME", "OTHER", "NOVEL", "DOUJINSHI",
                       "ANIME", "WEB_NOVEL", "LIVE_ACTION", "GAME", "COMIC", "MULTIMEDIA_PROJECT", "PICTURE_BOOK"]
MEDIA_SEASON = Literal["WINTER", "SPRING", "SUMMER", "FALL"]

STAFF_SORT = Literal["ID", "ID_DESC", "ROLE", "ROLE_DESC", "LANGUAGE", "LANGUAGE_DESC", "SEARCH_MATCH", "FAVOURITES",
                     "FAVOURITES_DESC", "RELEVANCE"]
CHARACTER_SORT = Literal[
    "ID", "ID_DESC", "ROLE", "ROLE_DESC", "SEARCH_MATCH", "FAVOURITES", "FAVOURITES_DESC", "RELEVANCE"]
STUDIO_SORT = Literal["ID", "ID_DESC", "NAME", "NAME_DESC", "SEARCH_MATCH", "FAVOURITES", "FAVOURITES_DESC"]
