"""AniList API enums — complete, generated from schema introspection."""

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal

# Media
MEDIA_TYPE = Literal["ANIME", "MANGA"]
MEDIA_FORMAT = Literal[
    "TV", "TV_SHORT", "MOVIE", "SPECIAL", "OVA", "ONA", "MUSIC",
    "MANGA", "NOVEL", "ONE_SHOT"
]
MEDIA_STATUS = Literal["FINISHED", "RELEASING", "NOT_YET_RELEASED", "CANCELLED", "HIATUS"]
MEDIA_SEASON = Literal["WINTER", "SPRING", "SUMMER", "FALL"]
MEDIA_SOURCE = Literal[
    "ORIGINAL", "MANGA", "LIGHT_NOVEL", "VISUAL_NOVEL", "VIDEO_GAME", "OTHER",
    "NOVEL", "DOUJINSHI", "ANIME", "WEB_NOVEL", "LIVE_ACTION", "GAME", "COMIC",
    "MULTIMEDIA_PROJECT", "PICTURE_BOOK"
]
MEDIA_SORT = Literal[
    "ID", "ID_DESC", "TITLE_ROMAJI", "TITLE_ROMAJI_DESC", "TITLE_ENGLISH",
    "TITLE_ENGLISH_DESC", "TITLE_NATIVE", "TITLE_NATIVE_DESC", "TYPE", "TYPE_DESC",
    "FORMAT", "FORMAT_DESC", "START_DATE", "START_DATE_DESC", "END_DATE", "END_DATE_DESC",
    "SCORE", "SCORE_DESC", "POPULARITY", "POPULARITY_DESC", "TRENDING", "TRENDING_DESC",
    "EPISODES", "EPISODES_DESC", "DURATION", "DURATION_DESC", "STATUS", "STATUS_DESC",
    "CHAPTERS", "CHAPTERS_DESC", "VOLUMES", "VOLUMES_DESC", "UPDATED_AT", "UPDATED_AT_DESC",
    "SEARCH_MATCH", "FAVOURITES", "FAVOURITES_DESC"
]
MEDIA_RELATION = Literal[
    "ADAPTATION", "PREQUEL", "SEQUEL", "PARENT", "SIDE_STORY", "CHARACTER",
    "SUMMARY", "ALTERNATIVE", "SPIN_OFF", "OTHER", "SOURCE", "COMPILATION", "CONTAINS"
]
MEDIA_RANK_TYPE = Literal["RATED", "POPULAR"]
MEDIA_LIST_STATUS = Literal["CURRENT", "PLANNING", "COMPLETED", "DROPPED", "PAUSED", "REPEATING"]

# Character
CHARACTER_SORT = Literal[
    "ID", "ID_DESC", "ROLE", "ROLE_DESC", "SEARCH_MATCH",
    "FAVOURITES", "FAVOURITES_DESC", "RELEVANCE"
]
CHARACTER_ROLE = Literal["MAIN", "SUPPORTING", "BACKGROUND"]

# Staff
STAFF_SORT = Literal[
    "ID", "ID_DESC", "ROLE", "ROLE_DESC", "LANGUAGE", "LANGUAGE_DESC",
    "SEARCH_MATCH", "FAVOURITES", "FAVOURITES_DESC", "RELEVANCE"
]

# Studio
STUDIO_SORT = Literal[
    "ID", "ID_DESC", "NAME", "NAME_DESC", "SEARCH_MATCH",
    "FAVOURITES", "FAVOURITES_DESC"
]

# External Links
EXTERNAL_LINK_TYPE = Literal["INFO", "STREAMING", "SOCIAL"]

# Reviews
REVIEW_SORT = Literal[
    "ID", "ID_DESC", "SCORE", "SCORE_DESC", "RATING", "RATING_DESC",
    "CREATED_AT", "CREATED_AT_DESC", "UPDATED_AT", "UPDATED_AT_DESC"
]
REVIEW_RATING = Literal["NO_VOTE", "UP_VOTE", "DOWN_VOTE"]

# Recommendations
RECOMMENDATION_SORT = Literal["ID", "ID_DESC", "RATING", "RATING_DESC"]
RECOMMENDATION_RATING = Literal["NO_RATING", "RATE_UP", "RATE_DOWN"]

# User
USER_SORT = Literal[
    "ID", "ID_DESC", "USERNAME", "USERNAME_DESC", "WATCHED_TIME", "WATCHED_TIME_DESC",
    "CHAPTERS_READ", "CHAPTERS_READ_DESC", "SEARCH_MATCH"
]
SCORE_FORMAT = Literal["POINT_100", "POINT_10_DECIMAL", "POINT_10", "POINT_5", "POINT_3"]

# Airing
AIRING_SORT = Literal[
    "ID", "ID_DESC", "MEDIA_ID", "MEDIA_ID_DESC",
    "TIME", "TIME_DESC", "EPISODE", "EPISODE_DESC"
]

# Trends
MEDIA_TREND_SORT = Literal[
    "ID", "ID_DESC", "MEDIA_ID", "MEDIA_ID_DESC", "DATE", "DATE_DESC",
    "SCORE", "SCORE_DESC", "POPULARITY", "POPULARITY_DESC",
    "TRENDING", "TRENDING_DESC", "EPISODE", "EPISODE_DESC"
]

# Activity
ACTIVITY_TYPE = Literal["TEXT", "ANIME_LIST", "MANGA_LIST", "MESSAGE", "MEDIA_LIST"]
ACTIVITY_SORT = Literal["ID", "ID_DESC", "PINNED"]

# Threads
THREAD_SORT = Literal[
    "ID", "ID_DESC", "TITLE", "TITLE_DESC",
    "CREATED_AT", "CREATED_AT_DESC", "UPDATED_AT", "UPDATED_AT_DESC",
    "REPLIED_AT", "REPLIED_AT_DESC", "REPLY_COUNT", "REPLY_COUNT_DESC",
    "VIEW_COUNT", "VIEW_COUNT_DESC", "IS_STICKY", "SEARCH_MATCH"
]
THREAD_COMMENT_SORT = Literal["ID", "ID_DESC"]

# Misc
LIKEABLE_TYPE = Literal["THREAD", "THREAD_COMMENT", "ACTIVITY", "ACTIVITY_REPLY"]
SITE_TREND_SORT = Literal["DATE", "DATE_DESC", "COUNT", "COUNT_DESC", "CHANGE", "CHANGE_DESC"]
NOTIFICATION_TYPE = Literal[
    "ACTIVITY_MESSAGE", "ACTIVITY_REPLY", "FOLLOWING", "ACTIVITY_MENTION",
    "THREAD_COMMENT_MENTION", "THREAD_SUBSCRIBED", "THREAD_COMMENT_REPLY",
    "AIRING", "ACTIVITY_LIKE", "ACTIVITY_REPLY_LIKE", "THREAD_LIKE",
    "THREAD_COMMENT_LIKE", "ACTIVITY_REPLY_SUBSCRIBED", "RELATED_MEDIA_ADDITION",
    "MEDIA_DATA_CHANGE", "MEDIA_MERGE", "MEDIA_DELETION"
]
